### PR TITLE
Now using CMake. Code and resources reorganized in folders.

### PR DESCRIPTION
**Pull request by Unarelith**
I propose this for the build system:
- Removing the `Makefile``
- Adding a `CMakeLists.txt` (to use: `cmake -B build . && cmake --build build -j8` or `mkdir build && cmake .. && make -j8` for older CMake versions)

I also reorganized the repo:
- Created a `resources` folder with two subfolders:
    - One for the shaders
    - One for the 3D models
- Created an `external` folder for the libraries
- Created a `source` folder for the actual code

Also, I renamed `Particule` to `Particle` in `main.cpp`.

### CODE REVIEW

**Comment by guibou** [comment]
Thank you.

Can you restore `default.nix` and add `cmake` in the `buildInputs` dependency field? Cmake does indeed provide dependency localisation on many systems, but the `default.nix` does actually provides theses dependencies.

**Review by guibou — CHANGES_REQUESTED** [review]
Restore default.nix and add `cmake` in the `buildInputs` field and I'll approvve.

**Comment by guibou** [comment]
Note for future pull requests. Your PR is doing too many things:

- Folder reorganization
- Typo correction (`Particules` -> `Particle`)
- Adding a cmake description

This is at least 3 pull requests.

Thank you for the cmake work.

**Comment by Unarelith** [comment]
Yeah I know, I was just too lazy to split my changes... :/

**Comment by guibou** [comment]
You'll do a wonderful haskell programer.

**Review by guibou — APPROVED** [review]

**Pull request merged**
